version: '3.4'

services:

  postgres:
    image: library/postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "meetup"
