spring:
  datasource:
    url: ${database.url}
    driver-class-name: org.postgresql.Driver
    username: ${database.user}
    password: ${database.password}
#  data:
#    jpa:
#      repositories:
#        enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    hibernate:
#      ddl-auto: none
#      use-new-id-generator-mappings: true
#      generate-ddl: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
#        jdbc.lob.non_contextual_creation: true
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8000

cors:
  allowedOrigins:
    - "*"

database:
  host: "localhost"
  port: 5432
  schema: "meetup"
  user: "admin"
  password: "admin"
  url: "jdbc:postgresql://${database.host}:${database.port}/${database.schema}?currentSchema=${database.schema}"
