CREATE TABLE meetup.subscription_payments
(
    ID UUID UNIQUE NOT NULL,
    PAYER_ID UUID NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    PERIOD VARCHAR(50) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    MONEY_VALUE DECIMAL(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP default CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT PK_SUBSCRIPTION_PAYMENTS PRIMARY KEY (ID)
)